import PptxGenJS from "pptxgenjs";

export interface PptSlideData {
    title: string;
    content: string[]; // Bullet points or paragraphs
    type: 'Title' | 'Content' | 'Section';
    notes?: string;
}

export class PresentationService {
    private pres: PptxGenJS;

    constructor() {
        this.pres = new PptxGenJS();
        this.setupTheme();
    }

    private setupTheme() {
        // Define 'Corporate' Master Slide
        this.pres.defineSlideMaster({
            title: "MASTER_SLIDE",
            background: { color: "F3F4F6" }, // Light gray background
            slideNumber: { x: "90%", y: "90%", fontSize: 10, color: "6B7280" },
            objects: [
                // Header Bar
                { rect: { x: 0, y: 0, w: "100%", h: 0.75, fill: { color: "111827" } } }, // Dark dark blue/black
                // Footer / Logo Placeholder
                { text: { text: "Generated by URA", options: { x: 0.5, y: "90%", w: "100%", align: "left", fontSize: 10, color: "6B7280" } } }
            ]
        });
    }

    public generatePresentation(slides: PptSlideData[]): Promise<Buffer> {
        if (!slides || slides.length === 0) {
            throw new Error("No slides provided to generate presentation");
        }

        // 1. Title Slide (First slide usually)
        const hasTitle = slides[0].type === 'Title';
        if (hasTitle) {
            const titleSlide = slides[0];
            const slide = this.pres.addSlide();
            slide.background = { color: "111827" }; // Dark background for Title Slide
            slide.addText(titleSlide.title, { x: 1, y: "40%", w: "80%", fontSize: 36, color: "FFFFFF", align: "center", bold: true });
            if (titleSlide.content.length > 0) {
                slide.addText(titleSlide.content.join("\n"), { x: 1, y: "55%", w: "80%", fontSize: 18, color: "9CA3AF", align: "center" });
            }
        }

        // 2. Content Slides
        const startIndex = hasTitle ? 1 : 0;
        for (let i = startIndex; i < slides.length; i++) {
            const sData = slides[i];
            const slide = this.pres.addSlide({ masterName: "MASTER_SLIDE" });

            // Title
            slide.addText(sData.title, { x: 0.5, y: 0.15, w: "90%", h: 0.5, fontSize: 24, color: "FFFFFF", bold: true, fontFace: "Arial" });

            // Content (Bullets)
            // Handle content array as bullet points
            const bullets = sData.content.map(text => ({ text, options: { breakLine: true, bullet: true } }));

            if (bullets.length > 0) {
                slide.addText(bullets, { x: 0.5, y: 1.0, w: "90%", h: 4.5, fontSize: 16, color: "374151", lineSpacing: 28 });
            }

            // Notes
            if (sData.notes) {
                slide.addNotes(sData.notes);
            }
        }

        // Return Buffer
        return this.pres.write({ outputType: "nodebuffer" }) as Promise<Buffer>;
    }
}
